In [ ]:
#Create a numpy array on your own and perform the following operations:
# array creation & initialization
# Mathematical & arithmetic operations
# Indexing, Slicing, Filtering


import numpy as np

# Array Creation and Initialization

a= np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

b= np.array([[9, 8, 7],
             [6, 5, 4],
             [3, 2, 1]])

arr= np.zeros((3,3))
print(arr)
arr=np.ones((3,3))
print(arr)
arr=np.eye(3)
print(arr)

# Matrix Arithmetic Operations

print("\nAddition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", (a / b).round())

# Matrix Multiplication (Dot Product)
print("Dot Product:\n", a@b)

# Transpose of A & B
print("\n Trasnpose A:\n", a.T)
print("\n Transpose B:\n", b.T)

# Indexing, Slicing, Filtering

print("\n")
print("\n",a)

print("0x2: \n", a[0,2])
print("1x1: \n", a[1,1])

print("\n",b)
print("0x1: \n", b[0,1])
print("2x2: \n", b[2,2])

print("\n")

print("Slicing the array ")
print(a[:2, :2])
print("\n")
print(a[1:, :1])
print("\n")
print(a[2:])
print("\n")
print(a[1:])

print("\n")

print("Filtering \n")
print(a[a>1])
print("\n")
print(a[a % 2 == 0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Division:
 [[0. 0. 0.]
 [1. 1. 2.]
 [2. 4. 9.]]
Dot Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

 Trasnpose A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

 Transpose B:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]



 [[1 2 3]
 [4 5 6]
 [7 8 9]]
0x2: 
 3
1x1: 
 5

 [[9 8 7]
 [6 5 4]
 [3 2 1]]
0x1: 
 8
2x2: 
 1


Slicing the array 
[[1 2]
 [4 5]]


[[4]
 [7]]


[[7 8 9]]


[[4 5 6]
 [7 8 9]]


Filtering 

[2 3 4 5 6 7 8 9]


[2 4 6 8]
